name: /r/TransDIY Wiki
on:

  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 5"

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check for 404
        run: |
          urls=("https://libreddit.pussthecat.org/r/TransDIY/wiki/pharmacies" "https://libreddit.pussthecat.org/r/TransDIY/wiki")
          failed=""
          for url in "${urls[@]}"; do
            status=$(curl -o /dev/null -s -w "%{http_code}" $url)
            if [ $status -eq 404 ]; then
              failed=$url
              echo "Got 404 on $failed. Exiting."
              curl -H "Content-Type: application/json" -d "{\"content\": \"${{ secrets.DISCORD_USER_ID }} $url returned 404\"}" ${{ secrets.WEBHOOK_URL }}
            fi
          done
      - name: download TransDIY
        run: |
          rm -rf libreddit.pussthecat.org && rm -rf reddit
          wget -mkxKEnp -e robots=off --header="Cookie: over18:1" --page-requisites --limit-rate=10m --random-wait -U 'Mozilla/5.0 (Linux; U; Android 10; SM-G960F Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/95.0.4638.50 Mobile Safari/537.36 OPR/60.0.2254.59405' https://libreddit.pussthecat.org/r/transdiy/wiki https://libreddit.pussthecat.org/r/transdiy/wiki/pharmacies || true
          mv libreddit.pussthecat.org reddit
          cd reddit/r/transdiy && rm *.orig && cd wiki && rm *.orig || true
      - name: commit changes
        if: ${{ success() }}
        uses: EndBug/add-and-commit@v9
        with:
          add: reddit
          pull: --rebase --autostash .
          message: "[automated] update /r/TransDIY wiki"
          default_author: github_actions
