name: Update DIYHRT.cafe links

on:
  workflow_dispatch:
  schedule:
    - cron: "30 23 1 * *" # every 1st of month 

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: pypy-3.7-v7.3.3
      - name: Download .cafe
        if: always()
        run: |
          rm cafe.txt
          pip install beautifulsoup4 bs4
          python getlinks.py 'https://diyhrt.cafe/index.php/Special:AllPages' > cafe.txt
          python formatlinks.py cafe.txt
      - name: Commit changes
        if: ${{ success() }}
        uses: EndBug/add-and-commit@v9
        with:
          add: "cafe.txt"
          pull: "--rebase --autostash ."
          message: "[automated] update diyhrt.cafe list"
          default_author: github_actions
